CREATE TABLE IF NOT EXISTS `rsib_sessions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `config_json` longtext NOT NULL,
  `param_grid_json` longtext DEFAULT NULL,
  `hmm_json` longtext DEFAULT NULL,
  `profit_json` longtext DEFAULT NULL,
  `total_combos` int NOT NULL DEFAULT 0,
  `completed` int NOT NULL DEFAULT 0,
  `total_variants` int NOT NULL DEFAULT 0,
  `status` varchar(20) NOT NULL DEFAULT 'pending',
  `best_profit` float DEFAULT NULL,
  `best_final_bank` float DEFAULT NULL,
  `total_time_sec` float NOT NULL DEFAULT 0,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_rsib_created` (`created_at`),
  KEY `idx_rsib_status` (`status`),
  KEY `idx_rsib_best_profit` (`best_profit` DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `rsib_results` (
  `id` int NOT NULL AUTO_INCREMENT,
  `session_id` int NOT NULL,
  `super_run_id` int DEFAULT NULL,
  `combo_index` int NOT NULL,
  `variant_type` varchar(32) NOT NULL,
  `variant_label` varchar(255) DEFAULT NULL,
  `strategy` varchar(64) NOT NULL,
  `strategy_params_json` longtext DEFAULT NULL,
  `sweep_id` int DEFAULT NULL,
  `sweep_combo_index` int DEFAULT NULL,
  `accuracy_pct` float DEFAULT NULL,
  `signals` int DEFAULT NULL,
  `correct` int DEFAULT NULL,
  `wrong` int DEFAULT NULL,
  `trades_taken` int DEFAULT NULL,
  `trades_skipped` int DEFAULT NULL,
  `monthly_json` longtext DEFAULT NULL,
  `metrics_json` longtext DEFAULT NULL,
  `final_bank_half` float DEFAULT NULL,
  `profit_half` float DEFAULT NULL,
  `roi_half` float DEFAULT NULL,
  `final_bank_full` float DEFAULT NULL,
  `profit_full` float DEFAULT NULL,
  `roi_full` float DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_rsib_results_session` (`session_id`),
  KEY `idx_rsib_results_profit` (`profit_full` DESC),
  KEY `idx_rsib_results_run` (`super_run_id`),
  KEY `idx_rsib_results_sweep` (`sweep_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
